In [2]:
import pandas as pd
import numpy as np

In [8]:
lst1=[1,2,3]
a=np.array(lst1)
a

array([1, 2, 3])

In [9]:
type(a)

numpy.ndarray

In [10]:
a.ndim

1

In [12]:
a.shape

(3,)

In [14]:
a.size

3

In [16]:
b=np.array([[1,2],[3,4],[5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
b.shape

(3, 2)

In [21]:
b.size

6

In [23]:
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
#minimum dimention
ar1 = np.array([1,2,3,4,5],ndmin=2)
ar1

array([[1, 2, 3, 4, 5]])

In [28]:
#aarange method

In [31]:
ar2=np.arange(0,24)
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [36]:
# np.zeros
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [38]:
np.zeros((5,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [40]:
# np.ones
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [43]:
# numpy.asarray
y=[1,2,3,4,5]
w=np.asarray(y)
w

array([1, 2, 3, 4, 5])

In [44]:
x=(1,2,3)
np.array(x)

array([1, 2, 3])

In [45]:
x=[(1,2,4),(7,8)]
np.asarray(x)

array([(1, 2, 4), (7, 8)], dtype=object)

In [48]:
# linspace
np.linspace(10,20,5) #10 to 20 in 5 datas

array([10. , 12.5, 15. , 17.5, 20. ])

In [50]:
np.linspace(10,20,20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [52]:
np.linspace(10,20,5,endpoint=False)

array([10., 12., 14., 16., 18.])

In [53]:
np.linspace(10,20,5,retstep=True)

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)

In [55]:
np.linspace(10,30,8,retstep=True)

(array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
        24.28571429, 27.14285714, 30.        ]),
 2.857142857142857)

In [58]:
# logspace
np.logspace(1,2,4)

array([ 10.        ,  21.5443469 ,  46.41588834, 100.        ])

In [60]:
np.logspace(1,10,10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [67]:
# numpy indexing and slicing
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a[0]

0

In [66]:
a[8]

8

In [6]:
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [8]:
a[1:]

array([[3, 4, 5],
       [4, 5, 6]])

In [10]:
a[0:2][0]

array([1, 2, 3])

In [12]:
a[0:2][0][1]

2

In [13]:
a[...,1]  #consider all rows and select index 1 column

array([2, 4, 5])

In [16]:
a[2,...] #consider index 2 row and selct all column

array([4, 5, 6])

In [27]:
x = np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
m=np.array([np.nan,1,2,3,np.nan,4])
m

array([nan,  1.,  2.,  3., nan,  4.])

In [22]:
m[~np.isnan(m)]

array([1., 2., 3., 4.])

In [23]:
a = np.array([1,2,3])
b = np.array([2,3,4])
a*b

array([ 2,  6, 12])

In [24]:
a+5

array([6, 7, 8])

In [25]:
for x in np.nditer(a):
    print(x)

1
2
3


In [28]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
x.flat[4]

5

In [32]:
x.flatten()

array([1, 2, 3, 4, 5, 6])

In [33]:
x.T  #transpose

array([[1, 3, 5],
       [2, 4, 6]])

In [37]:
# concatenate
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[11,12,13],[14,15,16]])
np.concatenate([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [38]:
np.concatenate([a,b],axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [39]:
np.stack([a,b],0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [40]:
np.stack([a,b],1)

array([[[ 1,  2,  3],
        [11, 12, 13]],

       [[ 4,  5,  6],
        [14, 15, 16]]])

In [42]:
#split
a = np.arange(9)
b = np.split(a,3)

In [43]:
b

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [45]:
np.split(a,[4,6])

[array([0, 1, 2, 3]), array([4, 5]), array([6, 7, 8])]