In [3]:
import pandas as pd
import numpy as np

In [8]:
lst1=[1,2,3]
a=np.array(lst1)
a

array([1, 2, 3])

In [9]:
type(a)

numpy.ndarray

In [10]:
a.ndim

1

In [12]:
a.shape

(3,)

In [14]:
a.size

3

In [16]:
b=np.array([[1,2],[3,4],[5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
b.shape

(3, 2)

In [21]:
b.size

6

In [23]:
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
#minimum dimention
ar1 = np.array([1,2,3,4,5],ndmin=2)
ar1

array([[1, 2, 3, 4, 5]])

In [28]:
#aarange method

In [31]:
ar2=np.arange(0,24)
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [36]:
# np.zeros
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [38]:
np.zeros((5,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [40]:
# np.ones
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [43]:
# numpy.asarray
y=[1,2,3,4,5]
w=np.asarray(y)
w

array([1, 2, 3, 4, 5])

In [44]:
x=(1,2,3)
np.array(x)

array([1, 2, 3])

In [45]:
x=[(1,2,4),(7,8)]
np.asarray(x)

array([(1, 2, 4), (7, 8)], dtype=object)

In [48]:
# linspace
np.linspace(10,20,5) #10 to 20 in 5 datas

array([10. , 12.5, 15. , 17.5, 20. ])

In [50]:
np.linspace(10,20,20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [52]:
np.linspace(10,20,5,endpoint=False)

array([10., 12., 14., 16., 18.])

In [53]:
np.linspace(10,20,5,retstep=True)

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)

In [55]:
np.linspace(10,30,8,retstep=True)

(array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
        24.28571429, 27.14285714, 30.        ]),
 2.857142857142857)

In [58]:
# logspace
np.logspace(1,2,4)

array([ 10.        ,  21.5443469 ,  46.41588834, 100.        ])

In [60]:
np.logspace(1,10,10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [67]:
# numpy indexing and slicing
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a[0]

0

In [66]:
a[8]

8